# fly.toml app configuration file generated for clearmark on 2025-05-04T15:55:29+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "clearmark"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
